name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'
    
    - name: List Direcory
      run: ls ble-apps/build/common/gcc

    - name: build application
      run: make -f ble-apps/build/common/gcc/build.mk
