name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10-2020-q4'
    
    - name: List Direcory
      run: ls controller/build/ble5-ctr/gcc

    - name: build application
      run: make build -f controller/build/ble5-ctr/gcc/makefile
